name: PurePerms
main: _64FF00\PurePerms\PurePerms
version: "INDEV"
api: [1.7.0]
load: STARTUP
author: 64FF00
website: https://github.com/64FF00/PurePerms
permissions:
  pperms:
    description: ""
    children:
      pperms.command:
        description: ""
        children:
          pperms.command.addgroup:
            description: "Allows you to add a new group to the groups list."
          pperms.command.groups:
            description: "Allows you to see a list of all groups."
          pperms.command.ppinfo:
            description: "Allows you to see info about PurePerms."
          pperms.command.ppreload:
            description: "Allows you to reload all PurePerms configurations."
          pperms.command.removegroup:
            description: "Allows you to remove a group from the groups list."
          pperms.command.setgperm:
            description: "Allows you to add a permission to the group."
          pperms.command.setgroup:
            description: "Allows you to set group for a user."
          pperms.command.setuperm:
            description: "Allows you to add a permission to a user."
          pperms.command.unsetgperm:
            description: "Allows you to remove a permission from the group."
          pperms.command.unsetuperm:
            description: "Allows you to remove a permission from the user."