name: PurePerms
main: _64FF00\PurePerms\PurePerms
version: "INDEV"
api: [1.7.0]
load: STARTUP
author: 64FF00
website: https://github.com/64FF00/PurePerms
permissions:
  pperms:
    description: ""
    children:
      pperms.command:
        description: ""
        children:
          pperms.command.addgroup:
            description: ""
          pperms.command.grouplist:
            description: ""
          pperms.command.ppinfo:
            description: ""
          pperms.command.ppreload:
            description: ""
          pperms.command.removegroup:
            description: ""
          pperms.command.setgperm:
            description: ""
          pperms.command.setgroup:
            description: ""
          pperms.command.setuperm:
            description: ""
          pperms.command.unsetgperm:
            description: ""
          pperms.command.unsetuperm:
            description: ""